# Generated by Django 5.1.1 on 2024-10-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand name')),
                ('car_model', models.CharField(max_length=100, verbose_name='Car model')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title of the service')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price of the service')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_number', models.CharField(max_length=10, verbose_name='Car national number')),
                ('vin_code', models.CharField(max_length=50, verbose_name='Vin code of the car')),
                ('client', models.CharField(max_length=50, verbose_name='Client Name')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.car')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantiti of the order')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.service')),
            ],
        ),
    ]
