# Generated by Django 5.1.1 on 2024-10-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='national_number',
            new_name='car_plate',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='client',
            new_name='client_name',
        ),
    ]
