# Generated by Django 5.1.1 on 2024-10-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_remove_order_total_price_alter_orderline_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Car Model', 'verbose_name_plural': 'Car Models'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Order Line', 'verbose_name_plural': 'Order Lines'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity of the order'),
        ),
    ]
