# Generated by Django 5.1.1 on 2024-10-15 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Gamintojas')),
                ('model', models.CharField(max_length=100, verbose_name='Modelis')),
            ],
            options={
                'verbose_name': 'Modelis',
                'verbose_name_plural': 'Modeliai',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Paslauga')),
                ('price', models.FloatField(verbose_name='Kaina')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, verbose_name='Valstybinis numeris')),
                ('vin_code', models.CharField(max_length=20, verbose_name='VIN kodas')),
                ('client_name', models.CharField(max_length=50, verbose_name='Klientas')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.carmodel', verbose_name='Modelis')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('a', 'Administruojamas'), ('v', 'Vykdomas'), ('i', 'Įvykdytas'), ('p', 'Atmestas')], default='a', max_length=1, verbose_name='Būsena')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autoservice.car', verbose_name='Automobilis')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Kiekis')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='autoservice.order', verbose_name='Užsakymas')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service', verbose_name='Paslauga')),
            ],
            options={
                'verbose_name': 'Eilutė',
                'verbose_name_plural': 'Eilutės',
            },
        ),
    ]
